"""empty message

Revision ID: e0b9105a5076
Revises: e437d88034f8
Create Date: 2022-08-16 16:13:35.178183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b9105a5076'
down_revision = 'e437d88034f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'instrument')
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'genres')
    op.add_column('artist', sa.Column('instrument', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
